import { IntentType, ReceiptStatus, RiskLevel } from "./domain.mjs";

export const providerDirectory = [
  {
    providerId: "stellar-agent-merchant-lab",
    name: "Stellar Agent Merchant Lab",
    category: "pay_service",
    description: "Independent MCP and MPP merchant sandbox for reproducible Stellar testnet purchases.",
    endpoint: "https://stellar-agent-merchant-lab.vercel.app/api/resource/stellar-risk-snapshot",
    paymentMethod: "stellar-mpp-usdc",
    legalContextUrl: "https://stellar-agent-merchant-lab.vercel.app/.well-known/legal-context.json",
    privacyRequirement: "no-pii",
    tags: ["mcp", "mpp", "merchant sandbox", "testnet usdc"],
  },
  {
    providerId: "browserbase-mcp",
    name: "Browserbase MCP",
    category: "pay_service",
    description: "Browser automation API payable by agentic payment flow.",
    endpoint: "https://mpp.example/services/browserbase",
    paymentMethod: "stellar-usdc-simulated",
    legalContextUrl: "https://browserbase.example/.well-known/legal-context.json",
    privacyRequirement: "no-pii",
    tags: ["mcp", "web browsing api", "agent tools"],
  },
  {
    providerId: "exa-api",
    name: "Exa Search API",
    category: "pay_service",
    description: "Search API credits for agent research workflows.",
    endpoint: "https://mpp.example/services/exa",
    paymentMethod: "stellar-usdc-simulated",
    legalContextUrl: "https://exa.example/.well-known/legal-context.json",
    privacyRequirement: "no-pii",
    tags: ["api", "search", "mcp"],
  },
  {
    providerId: "link-commerce-demo",
    name: "Link Commerce Demo",
    category: "pay_service",
    description: "Fiat delegated wallet checkout with approval-gated SPT or one-time credential.",
    endpoint: "link://agent-wallet/spend-request",
    paymentMethod: "link-agent-wallet-simulated",
    legalContextUrl: "https://link-commerce.example/.well-known/legal-context.json",
    privacyRequirement: "no-payment-credential-exposure",
    tags: ["link", "fiat", "spt", "agent wallet"],
  },
  {
    providerId: "stellar-swap",
    name: "Stellar DEX Swap",
    category: "buy_crypto",
    description: "Buy XLM or USDC under a portfolio spending policy.",
    endpoint: "stellar://dex/swap",
    paymentMethod: "stellar-smart-wallet",
    legalContextUrl: "https://stellar-swap.example/.well-known/legal-context.json",
    privacyRequirement: "wallet-only",
    tags: ["crypto", "portfolio", "swap"],
  },
  {
    providerId: "defindex-vault",
    name: "DeFindex Vault Placeholder",
    category: "defi_allocate",
    description: "Future yield allocation placeholder until contracts and docs are verified.",
    endpoint: "stellar://defindex/placeholder",
    paymentMethod: "stellar-smart-wallet",
    legalContextUrl: "https://defindex.example/.well-known/legal-context.json",
    privacyRequirement: "wallet-only",
    tags: ["defi", "vault", "yield"],
  },
  {
    providerId: "enel-cl",
    name: "Enel Chile Roadmap",
    category: "bill_pay",
    description: "IRL bill payment blocked until a ZK proof validates private account ownership.",
    endpoint: "partner-api://latam-billpay/enel",
    paymentMethod: "stellar-usdc-simulated",
    legalContextUrl: "https://enel.example/.well-known/legal-context.json",
    privacyRequirement: "zk-required",
    tags: ["bill", "latam", "privacy"],
  },
];

export const roadmapAccounts = [
  {
    id: "bill-enel-roadmap",
    providerId: "enel-cl",
    providerName: "Enel Chile",
    country: "CL",
    category: "bill_pay",
    alias: "Private account with commitment",
    customerRefCommitment: "0xcommitment_pending_demo",
    verificationStatus: "zk-proof-required",
    nextDueDate: "2026-06-29",
    domain: "enel.example",
  },
];

export const spendingPolicy = {
  dailyLimit: 120,
  monthlyLimit: 620,
  perPaymentLimit: 90,
  currency: "USDC",
  requireHumanConfirmation: true,
  autopilotEnabled: false,
  requireLegalContext: true,
  minLegalTrustLevel: 2,
  allowedAssets: ["USDC", "XLM"],
  allowedDefiProtocols: ["defindex"],
  maxPortfolioActionAmount: 75,
  maxSlippageBps: 80,
  allowlistedProviders: ["stellar-agent-merchant-lab", "browserbase-mcp", "exa-api", "link-commerce-demo", "stellar-swap", "defindex-vault", "enel-cl"],
  categoryRules: {
    pay_service: { autopay: false, maxAmount: 60 },
    buy_crypto: { autopay: false, maxAmount: 75 },
    defi_allocate: { autopay: false, maxAmount: 40 },
    bill_pay: { autopay: false, maxAmount: 70, proofRequired: true },
  },
};

export const legalContextRegistry = {
  "https://stellar-agent-merchant-lab.vercel.app/.well-known/legal-context.json": {
    termsText: "Stellar Agent Merchant Lab terms v1: testnet-only machine purchases, maximum price 0.01 USDC, explicit buyer confirmation, no personal data in payment metadata, and no claim that simulated receipts represent on-chain settlement.",
    legalContext: {
      terms: "https://stellar-agent-merchant-lab.vercel.app/terms/mpp-sandbox-v1.md",
      atrHash: "0xd3ec2999621a6b61f49e72c8057a2ee8162ac78c6a032a24abc5b7a596526b48",
      acceptanceRequired: false,
      trustLevel: 2,
      disputeResolution: { method: "public-receipt-review", jurisdiction: "testnet-sandbox" },
    },
  },
  "https://browserbase.example/.well-known/legal-context.json": {
    termsText: "Browserbase MCP demo terms: pay-per-call browser sessions, no personal data in payment metadata.",
    legalContext: {
      terms: "https://browserbase.example/terms/mpp-v1.md",
      atrHash: "0xf0dbe47fedc2156a9753404207fb03f61abe334b3c30c75c57662ea2c1bfe530",
      acceptanceRequired: true,
      trustLevel: 3,
      disputeResolution: { method: "usage-log-review", jurisdiction: "US" },
    },
  },
  "https://exa.example/.well-known/legal-context.json": {
    termsText: "Exa API demo terms: search credits for agent workflows, no secrets or account identifiers in request memos.",
    legalContext: {
      terms: "https://exa.example/terms/api-credits-v1.md",
      atrHash: "0x529dfe27e582d96399bc786007db40b816115920d2b03064d5f1e4f969881c7c",
      acceptanceRequired: false,
      trustLevel: 2,
      disputeResolution: { method: "api-usage-ticket", jurisdiction: "US" },
    },
  },
  "https://link-commerce.example/.well-known/legal-context.json": {
    termsText: "Link commerce demo terms: delegated wallet spend requests require human approval and never expose payment credentials to agents.",
    legalContext: {
      terms: "https://link-commerce.example/terms/agent-wallet-v1.md",
      atrHash: "0x8f2faee6d048fbb5004e90d6cf7c49232f545f8405d4f794b05c699f4f0e129e",
      acceptanceRequired: true,
      trustLevel: 3,
      disputeResolution: { method: "approval-log-review", jurisdiction: "US" },
    },
  },
  "https://stellar-swap.example/.well-known/legal-context.json": {
    termsText: "Stellar swap demo terms: simulated crypto purchase, user confirms all portfolio actions.",
    legalContext: {
      terms: "https://stellar-swap.example/terms/swap-v1.md",
      atrHash: "0x2ff4bab86967049db35d13b88d36feb1c07142a4f514f92d99b2afe94fc7efd1",
      acceptanceRequired: true,
      trustLevel: 3,
      disputeResolution: { method: "wallet-receipt-review", jurisdiction: "protocol" },
    },
  },
  "https://defindex.example/.well-known/legal-context.json": {
    termsText: "DeFindex placeholder terms: strategy not executable until contracts and risks are verified.",
    legalContext: {
      terms: "https://defindex.example/terms/placeholder-v1.md",
      atrHash: "0x6a134aef194f9a08dd5e56ca56b87911ecec6f306d8a5ebca63f170d6007bf21",
      acceptanceRequired: true,
      trustLevel: 3,
      disputeResolution: { method: "not-live", jurisdiction: "protocol" },
    },
  },
  "https://enel.example/.well-known/legal-context.json": {
    termsText: "Enel Chile roadmap terms: bill payment requires a valid ZK commitment proof and no raw account identifiers.",
    legalContext: {
      terms: "https://enel.example/terms/privacy-billpay-v1.md",
      atrHash: "0xca7fc1a964ba2dbad2ca94d978de23585c128acbaa049bd1f0c07cec34ebb545",
      acceptanceRequired: true,
      trustLevel: 3,
      disputeResolution: { method: "consumer-support", jurisdiction: "CL" },
    },
  },
};

export const demoProofs = {
  "intent-enel-private": {
    proofStatus: "missing",
    commitment: "0xcommitment_pending_demo",
    proofHash: null,
    privacyLevel: "zk-required",
  },
};

export const paymentIntents = [
  {
    id: "intent-link-commerce",
    intentType: IntentType.payService,
    providerId: "link-commerce-demo",
    providerName: "Link Commerce Demo",
    category: "pay_service",
    amount: 17.99,
    currency: "USD",
    dueDate: "2026-06-25",
    sourceOfFunds: "link-agent-wallet",
    riskLevel: RiskLevel.low,
    destinationAddress: "link://merchant/link-commerce-demo",
    legalContextUrl: "https://link-commerce.example/.well-known/legal-context.json",
    termsUrl: "https://link-commerce.example/terms/agent-wallet-v1.md",
    privacyRequirement: "no-payment-credential-exposure",
    proofRequired: false,
    proofStatus: "not-required",
    autopilotRequested: false,
    paymentMethod: "link-agent-wallet-simulated",
    linkPaymentMode: "shared_payment_token",
    publicMetadata: { approval: "required", credential: "tokenized", directory: "link-agent-wallet-pattern" },
    agentReason: "The agent can start the purchase, but the user approves before a tokenized credential is issued.",
  },
  {
    id: "intent-browserbase-mcp",
    intentType: IntentType.payService,
    providerId: "browserbase-mcp",
    providerName: "Browserbase MCP",
    category: "pay_service",
    amount: 18.5,
    currency: "USDC",
    dueDate: "2026-06-25",
    sourceOfFunds: "stellar-smart-wallet-usdc",
    riskLevel: RiskLevel.low,
    destinationAddress: "GCLMCPPAYMENTSIMULATED001",
    legalContextUrl: "https://browserbase.example/.well-known/legal-context.json",
    termsUrl: "https://browserbase.example/terms/mpp-v1.md",
    privacyRequirement: "no-pii",
    proofRequired: false,
    proofStatus: "not-required",
    autopilotRequested: false,
    publicMetadata: { units: "100 browser sessions", directory: "stripe-directory-pattern" },
    agentReason: "The agent needs browser sessions to research providers and the price is under the limit.",
  },
  {
    id: "intent-buy-xlm",
    intentType: IntentType.buyCrypto,
    providerId: "stellar-swap",
    providerName: "Stellar DEX Swap",
    category: "buy_crypto",
    amount: 55,
    currency: "USDC",
    dueDate: "2026-06-25",
    sourceOfFunds: "stellar-smart-wallet-usdc",
    riskLevel: RiskLevel.medium,
    destinationAddress: "GCLSTELLARSWAPSIMULATED002",
    legalContextUrl: "https://stellar-swap.example/.well-known/legal-context.json",
    termsUrl: "https://stellar-swap.example/terms/swap-v1.md",
    privacyRequirement: "wallet-only",
    proofRequired: false,
    proofStatus: "not-required",
    autopilotRequested: false,
    cryptoAction: { asset: "XLM", side: "buy", slippageBps: 45, risk: "medium" },
    publicMetadata: { route: "stellar-dex-simulated", quoteId: "quote_demo_xlm" },
    agentReason: "Buy a small amount of XLM for fees and Stellar ecosystem testing without exceeding slippage or the maximum amount.",
  },
  {
    id: "intent-defindex-alloc",
    intentType: IntentType.defiAllocate,
    providerId: "defindex-vault",
    providerName: "DeFindex Vault Placeholder",
    category: "defi_allocate",
    amount: 42,
    currency: "USDC",
    dueDate: "2026-06-25",
    sourceOfFunds: "stellar-smart-wallet-usdc",
    riskLevel: RiskLevel.medium,
    destinationAddress: "GCLDEFINDEXPLACEHOLDER003",
    legalContextUrl: "https://defindex.example/.well-known/legal-context.json",
    termsUrl: "https://defindex.example/terms/placeholder-v1.md",
    privacyRequirement: "wallet-only",
    proofRequired: false,
    proofStatus: "not-required",
    autopilotRequested: false,
    defiAllocation: { protocol: "defindex", strategy: "stable-yield-demo", risk: "medium", slippageBps: 60 },
    publicMetadata: { status: "placeholder-until-contracts-verified" },
    agentReason: "Prepare a DeFindex allocation for future integrations, but do not execute it until contracts are verified.",
  },
  {
    id: "intent-enel-private",
    intentType: IntentType.billPay,
    providerId: "enel-cl",
    providerName: "Enel Chile Roadmap",
    category: "bill_pay",
    amount: 43.8,
    currency: "USDC",
    dueDate: "2026-06-29",
    sourceOfFunds: "stellar-smart-wallet-usdc",
    riskLevel: RiskLevel.low,
    destinationAddress: "GCLENELBILLPAYMENTSIMULATED004",
    legalContextUrl: "https://enel.example/.well-known/legal-context.json",
    termsUrl: "https://enel.example/terms/privacy-billpay-v1.md",
    privacyRequirement: "zk-required",
    secretRefCommitment: "0xcommitment_pending_demo",
    proofRequired: true,
    proofStatus: "missing",
    autopilotRequested: false,
    publicMetadata: { account: "hidden-by-commitment", country: "CL" },
    agentReason: "Real-world payment stays blocked until private identifier ownership is proven without revealing the account number.",
  },
];

export const receipts = [
  {
    id: "receipt-demo-1",
    intentId: "intent-demo-api",
    providerId: "exa-api",
    providerName: "Exa Search API",
    intentType: IntentType.payService,
    category: "pay_service",
    amount: 12,
    currency: "USDC",
    status: ReceiptStatus.settled,
    timestamp: "2026-06-25T09:15:00.000Z",
    transactionHash: "stellar_demo_api_9f31",
    rail: "Stellar Smart Wallet",
    network: "stellar:testnet",
    asset: "USDC",
    finality: "simulated",
    reason: "API credits manually approved for the agent.",
    evidence: ["Provider verified in allowlist", "No PII in the public intent payload", "ATR hash verified"],
    approvedBy: "user-passkey",
    acceptedBy: "user-passkey",
    acceptedAt: "2026-06-25T09:15:00.000Z",
    termsHash: "0x529dfe27e582d96399bc786007db40b816115920d2b03064d5f1e4f969881c7c",
    proofHash: null,
    commitment: null,
    privacyLevel: "no-pii",
    legalContextSnapshot: {
      legalContextUrl: "https://exa.example/.well-known/legal-context.json",
      termsUrl: "https://exa.example/terms/api-credits-v1.md",
      atrHash: "0x529dfe27e582d96399bc786007db40b816115920d2b03064d5f1e4f969881c7c",
      acceptanceRequired: false,
      trustLevel: 2,
    },
  },
];