export const providerDirectory = [
  {
    providerId: "stellar-agent-merchant-lab",
    name: "Stellar Agent Merchant Lab",
    category: "pay_service",
    description: "Sandbox independiente MCP y MPP para compras reproducibles en Stellar testnet.",
    endpoint: "https://stellar-agent-merchant-lab.vercel.app/api/resource/stellar-risk-snapshot",
    paymentMethod: "stellar-mpp-usdc",
    legalContextUrl: "https://stellar-agent-merchant-lab.vercel.app/.well-known/legal-context.json",
    privacyRequirement: "no-pii",
    tags: ["mcp", "mpp", "merchant sandbox", "testnet usdc", "analizar", "transaccion", "riesgo", "pago"],
  },
  {
    providerId: "browserbase-mcp",
    name: "Browserbase MCP",
    category: "pay_service",
    description: "API de automatizacion de navegador, pagable por el flujo de pago del agente.",
    endpoint: "https://mpp.example/services/browserbase",
    paymentMethod: "stellar-usdc-simulated",
    legalContextUrl: "https://browserbase.example/.well-known/legal-context.json",
    privacyRequirement: "no-pii",
    tags: ["mcp", "web browsing api", "agent tools", "navegador", "sesiones", "web", "comprar"],
  },
  {
    providerId: "exa-api",
    name: "Exa Search API",
    category: "pay_service",
    description: "Creditos de API de busqueda para flujos de investigacion del agente.",
    endpoint: "https://mpp.example/services/exa",
    paymentMethod: "stellar-usdc-simulated",
    legalContextUrl: "https://exa.example/.well-known/legal-context.json",
    privacyRequirement: "no-pii",
    tags: ["api", "search", "mcp", "buscar", "informacion", "investigar", "web"],
  },
  {
    providerId: "link-commerce-demo",
    name: "Link Commerce Demo",
    category: "pay_service",
    description: "Checkout con wallet delegada en moneda fiat, con SPT o credencial de un solo uso sujeta a aprobacion.",
    endpoint: "link://agent-wallet/spend-request",
    paymentMethod: "link-agent-wallet-simulated",
    legalContextUrl: "https://link-commerce.example/.well-known/legal-context.json",
    privacyRequirement: "no-payment-credential-exposure",
    tags: ["link", "fiat", "spt", "agent wallet"],
  },
  {
    providerId: "firecrawl-mcp",
    name: "Firecrawl MCP Sandbox",
    category: "pay_service",
    description: "Convierte una pagina web en markdown o JSON estructurado para un flujo del agente.",
    endpoint: "https://mpp.example/services/firecrawl",
    paymentMethod: "stellar-usdc-simulated",
    legalContextUrl: "https://firecrawl.example/.well-known/legal-context.json",
    privacyRequirement: "no-pii",
    tags: ["mcp", "scrape", "website", "crawl", "extract", "markdown", "json", "extraer", "informacion", "web"],
  },
  {
    providerId: "dataset-snapshot-api",
    name: "Dataset Snapshot API",
    category: "pay_service",
    description: "Compra una muestra de datos pequena para tareas de mercado, investigacion o enriquecimiento.",
    endpoint: "https://mpp.example/services/dataset-snapshot",
    paymentMethod: "stellar-usdc-simulated",
    legalContextUrl: "https://dataset.example/.well-known/legal-context.json",
    privacyRequirement: "no-pii",
    tags: ["api", "dataset", "data", "market", "research", "snapshot", "enrichment", "datos", "muestra", "investigar", "json"],
  },
  {
    providerId: "mcp-sandbox-hosting",
    name: "MCP Sandbox Hosting",
    category: "pay_service",
    description: "Inicia un sandbox MCP de corta duracion para un experimento del agente.",
    endpoint: "https://mpp.example/services/mcp-sandbox",
    paymentMethod: "stellar-usdc-simulated",
    legalContextUrl: "https://mcp-sandbox.example/.well-known/legal-context.json",
    privacyRequirement: "no-pii",
    tags: ["mcp", "sandbox", "hosting", "tool", "server", "agent", "experiment", "preparar", "herramienta"],
  },
  {
    providerId: "cloud-credits-api",
    name: "Cloud Credits API",
    category: "pay_service",
    description: "Compra un paquete pequeno de creditos cloud/API prepagados para una tarea supervisada del agente.",
    endpoint: "https://mpp.example/services/cloud-credits",
    paymentMethod: "stellar-usdc-simulated",
    legalContextUrl: "https://cloud-credits.example/.well-known/legal-context.json",
    privacyRequirement: "no-pii",
    tags: ["cloud", "credits", "api", "compute", "storage", "developer", "google", "aws", "vercel", "creditos", "comprar"],
  },
  {
    providerId: "voice-preview-api",
    name: "Voice Preview API",
    category: "pay_service",
    description: "Genera una muestra corta de audio para un producto, demo o agente de soporte.",
    endpoint: "https://mpp.example/services/voice-preview",
    paymentMethod: "stellar-usdc-simulated",
    legalContextUrl: "https://voice-preview.example/.well-known/legal-context.json",
    privacyRequirement: "no-pii",
    tags: ["audio", "voice", "tts", "preview", "media", "generation", "generar", "corto", "voz"],
  },
  {
    providerId: "image-render-api",
    name: "Image Render API",
    category: "pay_service",
    description: "Genera una imagen liviana o tarjeta social para un recurso creado por el agente.",
    endpoint: "https://mpp.example/services/image-render",
    paymentMethod: "stellar-usdc-simulated",
    legalContextUrl: "https://image-render.example/.well-known/legal-context.json",
    privacyRequirement: "no-pii",
    tags: ["image", "render", "social", "card", "media", "artifact", "generation", "imagen", "demo", "crear"],
  },
  {
    providerId: "stellar-swap",
    name: "Stellar DEX Swap",
    category: "buy_crypto",
    description: "Compra XLM o USDC bajo una politica de gasto de portafolio.",
    endpoint: "stellar://dex/swap",
    paymentMethod: "stellar-smart-wallet",
    legalContextUrl: "https://stellar-swap.example/.well-known/legal-context.json",
    privacyRequirement: "wallet-only",
    tags: ["crypto", "portfolio", "swap"],
  },
  {
    providerId: "defindex-vault",
    name: "DeFindex Vault Placeholder",
    category: "defi_allocate",
    description: "Marcador de asignacion de rendimiento futuro, hasta verificar contratos y documentacion.",
    endpoint: "stellar://defindex/placeholder",
    paymentMethod: "stellar-smart-wallet",
    legalContextUrl: "https://defindex.example/.well-known/legal-context.json",
    privacyRequirement: "wallet-only",
    tags: ["defi", "vault", "yield"],
  },
  {
    providerId: "enel-cl",
    name: "Enel Chile Roadmap",
    category: "bill_pay",
    description: "Pago de cuenta real bloqueado hasta validar con prueba de privacidad la posesion de la cuenta.",
    endpoint: "partner-api://latam-billpay/enel",
    paymentMethod: "stellar-usdc-simulated",
    legalContextUrl: "https://enel.example/.well-known/legal-context.json",
    privacyRequirement: "zk-required",
    tags: ["bill", "latam", "privacy"],
  },
];

export const roadmapAccounts = [
  {
    id: "bill-enel-roadmap",
    providerId: "enel-cl",
    providerName: "Enel Chile",
    country: "CL",
    category: "bill_pay",
    alias: "Cuenta privada con compromiso",
    customerRefCommitment: "0xcommitment_pending_demo",
    verificationStatus: "zk-proof-required",
    nextDueDate: "2026-06-29",
    domain: "enel.example",
  },
];
