import { IntentType, ReceiptStatus, RiskLevel } from "./domain.mjs";

export const paymentIntents = [
  {
    id: "intent-link-commerce",
    intentType: IntentType.payService,
    providerId: "link-commerce-demo",
    providerName: "Link Commerce Demo",
    category: "pay_service",
    amount: 17.99,
    currency: "USD",
    dueDate: "2026-06-25",
    sourceOfFunds: "link-agent-wallet",
    riskLevel: RiskLevel.low,
    destinationAddress: "link://merchant/link-commerce-demo",
    legalContextUrl: "https://link-commerce.example/.well-known/legal-context.json",
    termsUrl: "https://link-commerce.example/terms/agent-wallet-v1.md",
    privacyRequirement: "no-payment-credential-exposure",
    proofRequired: false,
    proofStatus: "not-required",
    autopilotRequested: false,
    paymentMethod: "link-agent-wallet-simulated",
    linkPaymentMode: "shared_payment_token",
    publicMetadata: { approval: "required", credential: "tokenized", directory: "link-agent-wallet-pattern" },
    agentReason: "The agent can start the purchase, but the user approves before a tokenized credential is issued.",
  },
  {
    id: "intent-browserbase-mcp",
    intentType: IntentType.payService,
    providerId: "browserbase-mcp",
    providerName: "Browserbase MCP",
    category: "pay_service",
    amount: 18.5,
    currency: "USDC",
    dueDate: "2026-06-25",
    sourceOfFunds: "stellar-smart-wallet-usdc",
    riskLevel: RiskLevel.low,
    destinationAddress: "GCLMCPPAYMENTSIMULATED001",
    legalContextUrl: "https://browserbase.example/.well-known/legal-context.json",
    termsUrl: "https://browserbase.example/terms/mpp-v1.md",
    privacyRequirement: "no-pii",
    proofRequired: false,
    proofStatus: "not-required",
    autopilotRequested: false,
    publicMetadata: { units: "100 browser sessions", directory: "stripe-directory-pattern" },
    agentReason: "The agent needs browser sessions to research providers and the price is under the limit.",
  },
  {
    id: "intent-buy-xlm",
    intentType: IntentType.buyCrypto,
    providerId: "stellar-swap",
    providerName: "Stellar DEX Swap",
    category: "buy_crypto",
    amount: 55,
    currency: "USDC",
    dueDate: "2026-06-25",
    sourceOfFunds: "stellar-smart-wallet-usdc",
    riskLevel: RiskLevel.medium,
    destinationAddress: "GCLSTELLARSWAPSIMULATED002",
    legalContextUrl: "https://stellar-swap.example/.well-known/legal-context.json",
    termsUrl: "https://stellar-swap.example/terms/swap-v1.md",
    privacyRequirement: "wallet-only",
    proofRequired: false,
    proofStatus: "not-required",
    autopilotRequested: false,
    cryptoAction: { asset: "XLM", side: "buy", slippageBps: 45, risk: "medium" },
    publicMetadata: { route: "stellar-dex-simulated", quoteId: "quote_demo_xlm" },
    agentReason: "Buy a small amount of XLM for fees and Stellar ecosystem testing without exceeding slippage or the maximum amount.",
  },
  {
    id: "intent-defindex-alloc",
    intentType: IntentType.defiAllocate,
    providerId: "defindex-vault",
    providerName: "DeFindex Vault Placeholder",
    category: "defi_allocate",
    amount: 42,
    currency: "USDC",
    dueDate: "2026-06-25",
    sourceOfFunds: "stellar-smart-wallet-usdc",
    riskLevel: RiskLevel.medium,
    destinationAddress: "GCLDEFINDEXPLACEHOLDER003",
    legalContextUrl: "https://defindex.example/.well-known/legal-context.json",
    termsUrl: "https://defindex.example/terms/placeholder-v1.md",
    privacyRequirement: "wallet-only",
    proofRequired: false,
    proofStatus: "not-required",
    autopilotRequested: false,
    defiAllocation: { protocol: "defindex", strategy: "stable-yield-demo", risk: "medium", slippageBps: 60 },
    publicMetadata: { status: "placeholder-until-contracts-verified" },
    agentReason: "Prepare a DeFindex allocation for future integrations, but do not execute it until contracts are verified.",
  },
  {
    id: "intent-enel-private",
    intentType: IntentType.billPay,
    providerId: "enel-cl",
    providerName: "Enel Chile Roadmap",
    category: "bill_pay",
    amount: 43.8,
    currency: "USDC",
    dueDate: "2026-06-29",
    sourceOfFunds: "stellar-smart-wallet-usdc",
    riskLevel: RiskLevel.low,
    destinationAddress: "GCLENELBILLPAYMENTSIMULATED004",
    legalContextUrl: "https://enel.example/.well-known/legal-context.json",
    termsUrl: "https://enel.example/terms/privacy-billpay-v1.md",
    privacyRequirement: "zk-required",
    secretRefCommitment: "0xcommitment_pending_demo",
    proofRequired: true,
    proofStatus: "missing",
    autopilotRequested: false,
    publicMetadata: { account: "hidden-by-commitment", country: "CL" },
    agentReason: "Real-world payment stays blocked until private identifier ownership is proven without revealing the account number.",
  },
];

export const receipts = [
  {
    id: "receipt-demo-1",
    intentId: "intent-demo-api",
    providerId: "exa-api",
    providerName: "Exa Search API",
    intentType: IntentType.payService,
    category: "pay_service",
    amount: 12,
    currency: "USDC",
    status: ReceiptStatus.settled,
    timestamp: "2026-06-25T09:15:00.000Z",
    transactionHash: "stellar_demo_api_9f31",
    rail: "Stellar Smart Wallet",
    network: "stellar:testnet",
    asset: "USDC",
    finality: "simulated",
    reason: "API credits manually approved for the agent.",
    evidence: ["Provider verified in allowlist", "No PII in the public intent payload", "ATR hash verified"],
    approvedBy: "user-passkey",
    acceptedBy: "user-passkey",
    acceptedAt: "2026-06-25T09:15:00.000Z",
    termsHash: "0x529dfe27e582d96399bc786007db40b816115920d2b03064d5f1e4f969881c7c",
    proofHash: null,
    commitment: null,
    privacyLevel: "no-pii",
    legalContextSnapshot: {
      legalContextUrl: "https://exa.example/.well-known/legal-context.json",
      termsUrl: "https://exa.example/terms/api-credits-v1.md",
      atrHash: "0x529dfe27e582d96399bc786007db40b816115920d2b03064d5f1e4f969881c7c",
      acceptanceRequired: false,
      trustLevel: 2,
    },
  },
];
