export const providerDirectory = [
  {
    providerId: "stellar-agent-merchant-lab",
    name: "Stellar Agent Merchant Lab",
    category: "pay_service",
    description: "Independent MCP and MPP merchant sandbox for reproducible Stellar testnet purchases.",
    endpoint: "https://stellar-agent-merchant-lab.vercel.app/api/resource/stellar-risk-snapshot",
    paymentMethod: "stellar-mpp-usdc",
    legalContextUrl: "https://stellar-agent-merchant-lab.vercel.app/.well-known/legal-context.json",
    privacyRequirement: "no-pii",
    tags: ["mcp", "mpp", "merchant sandbox", "testnet usdc"],
  },
  {
    providerId: "browserbase-mcp",
    name: "Browserbase MCP",
    category: "pay_service",
    description: "Browser automation API payable by agentic payment flow.",
    endpoint: "https://mpp.example/services/browserbase",
    paymentMethod: "stellar-usdc-simulated",
    legalContextUrl: "https://browserbase.example/.well-known/legal-context.json",
    privacyRequirement: "no-pii",
    tags: ["mcp", "web browsing api", "agent tools"],
  },
  {
    providerId: "exa-api",
    name: "Exa Search API",
    category: "pay_service",
    description: "Search API credits for agent research workflows.",
    endpoint: "https://mpp.example/services/exa",
    paymentMethod: "stellar-usdc-simulated",
    legalContextUrl: "https://exa.example/.well-known/legal-context.json",
    privacyRequirement: "no-pii",
    tags: ["api", "search", "mcp"],
  },
  {
    providerId: "link-commerce-demo",
    name: "Link Commerce Demo",
    category: "pay_service",
    description: "Fiat delegated wallet checkout with approval-gated SPT or one-time credential.",
    endpoint: "link://agent-wallet/spend-request",
    paymentMethod: "link-agent-wallet-simulated",
    legalContextUrl: "https://link-commerce.example/.well-known/legal-context.json",
    privacyRequirement: "no-payment-credential-exposure",
    tags: ["link", "fiat", "spt", "agent wallet"],
  },
  {
    providerId: "firecrawl-mcp",
    name: "Firecrawl MCP Sandbox",
    category: "pay_service",
    description: "Extract a website into structured markdown or JSON for an agent workflow.",
    endpoint: "https://mpp.example/services/firecrawl",
    paymentMethod: "stellar-usdc-simulated",
    legalContextUrl: "https://firecrawl.example/.well-known/legal-context.json",
    privacyRequirement: "no-pii",
    tags: ["mcp", "scrape", "website", "crawl", "extract", "markdown", "json"],
  },
  {
    providerId: "dataset-snapshot-api",
    name: "Dataset Snapshot API",
    category: "pay_service",
    description: "Purchase a small data snapshot for market, research or enrichment tasks.",
    endpoint: "https://mpp.example/services/dataset-snapshot",
    paymentMethod: "stellar-usdc-simulated",
    legalContextUrl: "https://dataset.example/.well-known/legal-context.json",
    privacyRequirement: "no-pii",
    tags: ["api", "dataset", "data", "market", "research", "snapshot", "enrichment"],
  },
  {
    providerId: "mcp-sandbox-hosting",
    name: "MCP Sandbox Hosting",
    category: "pay_service",
    description: "Start a short-lived MCP tool sandbox for an agent experiment.",
    endpoint: "https://mpp.example/services/mcp-sandbox",
    paymentMethod: "stellar-usdc-simulated",
    legalContextUrl: "https://mcp-sandbox.example/.well-known/legal-context.json",
    privacyRequirement: "no-pii",
    tags: ["mcp", "sandbox", "hosting", "tool", "server", "agent", "experiment"],
  },
  {
    providerId: "cloud-credits-api",
    name: "Cloud Credits API",
    category: "pay_service",
    description: "Buy a tiny prepaid cloud/API credit pack for a supervised agent task.",
    endpoint: "https://mpp.example/services/cloud-credits",
    paymentMethod: "stellar-usdc-simulated",
    legalContextUrl: "https://cloud-credits.example/.well-known/legal-context.json",
    privacyRequirement: "no-pii",
    tags: ["cloud", "credits", "api", "compute", "storage", "developer", "google", "aws", "vercel"],
  },
  {
    providerId: "voice-preview-api",
    name: "Voice Preview API",
    category: "pay_service",
    description: "Generate a short audio preview for a product, demo or support agent.",
    endpoint: "https://mpp.example/services/voice-preview",
    paymentMethod: "stellar-usdc-simulated",
    legalContextUrl: "https://voice-preview.example/.well-known/legal-context.json",
    privacyRequirement: "no-pii",
    tags: ["audio", "voice", "tts", "preview", "media", "generation"],
  },
  {
    providerId: "image-render-api",
    name: "Image Render API",
    category: "pay_service",
    description: "Render a lightweight image or social card for an agent-generated artifact.",
    endpoint: "https://mpp.example/services/image-render",
    paymentMethod: "stellar-usdc-simulated",
    legalContextUrl: "https://image-render.example/.well-known/legal-context.json",
    privacyRequirement: "no-pii",
    tags: ["image", "render", "social", "card", "media", "artifact", "generation"],
  },
  {
    providerId: "stellar-swap",
    name: "Stellar DEX Swap",
    category: "buy_crypto",
    description: "Buy XLM or USDC under a portfolio spending policy.",
    endpoint: "stellar://dex/swap",
    paymentMethod: "stellar-smart-wallet",
    legalContextUrl: "https://stellar-swap.example/.well-known/legal-context.json",
    privacyRequirement: "wallet-only",
    tags: ["crypto", "portfolio", "swap"],
  },
  {
    providerId: "defindex-vault",
    name: "DeFindex Vault Placeholder",
    category: "defi_allocate",
    description: "Future yield allocation placeholder until contracts and docs are verified.",
    endpoint: "stellar://defindex/placeholder",
    paymentMethod: "stellar-smart-wallet",
    legalContextUrl: "https://defindex.example/.well-known/legal-context.json",
    privacyRequirement: "wallet-only",
    tags: ["defi", "vault", "yield"],
  },
  {
    providerId: "enel-cl",
    name: "Enel Chile Roadmap",
    category: "bill_pay",
    description: "IRL bill payment blocked until a ZK proof validates private account ownership.",
    endpoint: "partner-api://latam-billpay/enel",
    paymentMethod: "stellar-usdc-simulated",
    legalContextUrl: "https://enel.example/.well-known/legal-context.json",
    privacyRequirement: "zk-required",
    tags: ["bill", "latam", "privacy"],
  },
];

export const roadmapAccounts = [
  {
    id: "bill-enel-roadmap",
    providerId: "enel-cl",
    providerName: "Enel Chile",
    country: "CL",
    category: "bill_pay",
    alias: "Private account with commitment",
    customerRefCommitment: "0xcommitment_pending_demo",
    verificationStatus: "zk-proof-required",
    nextDueDate: "2026-06-29",
    domain: "enel.example",
  },
];
